In [2]:
import numpy as np

In [3]:
array=np.array([157, 161, 152, 167, 190, 180, 183, 158, 175, 179, 154, 160, 155,
                 163, 166, 172, 189, 156, 171, 174, 169, 164, 185, 150, 177, 168,
                 186, 153, 182, 188, 173, 162, 170, 184, 187, 151, 176, 159, 165,
                 178, 181, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

In [23]:
import random

# Define list size
list_size = 200

# Create an empty list
my_list = []

# Add some specific negative numbers
specific_negatives = [-13, -25, -77, -99]

# Generate random integers between -100 (inclusive) and 0 (exclusive)
for _ in range(list_size - len(specific_negatives)):
  my_list.append(random.randint(-100, 0))

# Add the specific negative numbers to the list
my_list.extend(specific_negatives)

# Print the random list
print(my_list)



[-99, -28, -55, -17, -63, -35, -15, -29, -67, -77, -64, -66, -38, 0, -25, -60, -1, -42, 0, -60, -40, -60, -57, -97, -5, -16, -41, -24, -29, -32, -24, -30, -90, -96, -75, -44, -63, -5, -33, -75, -14, -23, -47, -85, -17, -41, -43, -54, -63, -43, -55, -25, -48, -69, -58, -6, -67, -45, -61, -29, -10, -36, -27, -62, -93, -12, -98, -17, -9, -49, -48, -75, -45, -48, -66, -99, -73, -58, -61, -28, -26, -82, -57, -78, -35, -13, -72, -9, -74, -74, -44, -21, -46, -25, -67, -46, -68, -10, -25, -28, -2, -88, -47, -90, -56, -67, -100, -97, -96, -38, -5, -29, -17, -34, -99, -9, -12, -90, -17, -82, -9, -9, -33, -67, -67, -83, -8, -14, -45, -8, -39, -55, -89, -95, -5, -18, -88, -56, -33, -9, -13, -11, -95, -28, -86, 0, -11, -5, -71, -65, -60, -19, -91, -24, -64, -64, -72, -35, -85, -22, -31, -77, -50, -51, -57, -1, -98, -93, -33, -96, -39, -44, -65, -78, -19, -21, -43, -97, -14, -91, -55, -77, -18, -86, -2, -96, -3, -21, -21, -34, -75, -100, -17, -73, -8, -94, -13, -25, -77, -99]


In [24]:
print(array)    

[157 161 152 167 190 180 183 158 175 179 154 160 155 163 166 172 189 156
 171 174 169 164 185 150 177 168 186 153 182 188 173 162 170 184 187 151
 176 159 165 178 181 191 192 193 194 195 196 197 198 199 200]


In [25]:
np.sqrt(array)

array([12.52996409, 12.68857754, 12.32882801, 12.92284798, 13.78404875,
       13.41640786, 13.52774926, 12.56980509, 13.22875656, 13.37908816,
       12.40967365, 12.64911064, 12.4498996 , 12.76714533, 12.88409873,
       13.11487705, 13.74772708, 12.489996  , 13.07669683, 13.19090596,
       13.        , 12.80624847, 13.60147051, 12.24744871, 13.3041347 ,
       12.9614814 , 13.6381817 , 12.36931688, 13.49073756, 13.7113092 ,
       13.15294644, 12.72792206, 13.03840481, 13.56465997, 13.67479433,
       12.28820573, 13.26649916, 12.60952021, 12.84523258, 13.34166406,
       13.45362405, 13.82027496, 13.85640646, 13.89244399, 13.92838828,
       13.96424004, 14.        , 14.03566885, 14.07124728, 14.10673598,
       14.14213562])

In [26]:
np.sqrt([1,2,4,5,6,7,8,9])

array([1.        , 1.41421356, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [32]:
my_list=np.array(my_list)

In [33]:
np.absolute(my_list)

array([ 99,  28,  55,  17,  63,  35,  15,  29,  67,  77,  64,  66,  38,
         0,  25,  60,   1,  42,   0,  60,  40,  60,  57,  97,   5,  16,
        41,  24,  29,  32,  24,  30,  90,  96,  75,  44,  63,   5,  33,
        75,  14,  23,  47,  85,  17,  41,  43,  54,  63,  43,  55,  25,
        48,  69,  58,   6,  67,  45,  61,  29,  10,  36,  27,  62,  93,
        12,  98,  17,   9,  49,  48,  75,  45,  48,  66,  99,  73,  58,
        61,  28,  26,  82,  57,  78,  35,  13,  72,   9,  74,  74,  44,
        21,  46,  25,  67,  46,  68,  10,  25,  28,   2,  88,  47,  90,
        56,  67, 100,  97,  96,  38,   5,  29,  17,  34,  99,   9,  12,
        90,  17,  82,   9,   9,  33,  67,  67,  83,   8,  14,  45,   8,
        39,  55,  89,  95,   5,  18,  88,  56,  33,   9,  13,  11,  95,
        28,  86,   0,  11,   5,  71,  65,  60,  19,  91,  24,  64,  64,
        72,  35,  85,  22,  31,  77,  50,  51,  57,   1,  98,  93,  33,
        96,  39,  44,  65,  78,  19,  21,  43,  97,  14,  91,  5

In [34]:
np.sqrt(my_list)

/tmp/ipykernel_4339/2689594228.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(my_list)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        0., nan, nan, nan, nan,  0., nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan,  0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [35]:
np.exp(my_list)

array([1.01122149e-43, 6.91440011e-13, 1.29958143e-24, 4.13993772e-08,
       4.35961000e-28, 6.30511676e-16, 3.05902321e-07, 2.54366565e-13,
       7.98490425e-30, 3.62514092e-34, 1.60381089e-28, 2.17052201e-29,
       3.13913279e-17, 1.00000000e+00, 1.38879439e-11, 8.75651076e-27,
       3.67879441e-01, 5.74952226e-19, 1.00000000e+00, 8.75651076e-27,
       4.24835426e-18, 8.75651076e-27, 1.75879220e-25, 7.47197234e-43,
       6.73794700e-03, 1.12535175e-07, 1.56288219e-18, 3.77513454e-11,
       2.54366565e-13, 1.26641655e-14, 3.77513454e-11, 9.35762297e-14,
       8.19401262e-40, 2.03109266e-42, 2.67863696e-33, 7.78113224e-20,
       4.35961000e-28, 6.73794700e-03, 4.65888615e-15, 2.67863696e-33,
       8.31528719e-07, 1.02618796e-10, 3.87399763e-21, 1.21609930e-37,
       4.13993772e-08, 1.56288219e-18, 2.11513104e-19, 3.53262857e-24,
       4.35961000e-28, 2.11513104e-19, 1.29958143e-24, 1.38879439e-11,
       1.42516408e-21, 1.08063928e-30, 6.47023493e-26, 2.47875218e-03,
      

In [36]:
my_list

array([ -99,  -28,  -55,  -17,  -63,  -35,  -15,  -29,  -67,  -77,  -64,
        -66,  -38,    0,  -25,  -60,   -1,  -42,    0,  -60,  -40,  -60,
        -57,  -97,   -5,  -16,  -41,  -24,  -29,  -32,  -24,  -30,  -90,
        -96,  -75,  -44,  -63,   -5,  -33,  -75,  -14,  -23,  -47,  -85,
        -17,  -41,  -43,  -54,  -63,  -43,  -55,  -25,  -48,  -69,  -58,
         -6,  -67,  -45,  -61,  -29,  -10,  -36,  -27,  -62,  -93,  -12,
        -98,  -17,   -9,  -49,  -48,  -75,  -45,  -48,  -66,  -99,  -73,
        -58,  -61,  -28,  -26,  -82,  -57,  -78,  -35,  -13,  -72,   -9,
        -74,  -74,  -44,  -21,  -46,  -25,  -67,  -46,  -68,  -10,  -25,
        -28,   -2,  -88,  -47,  -90,  -56,  -67, -100,  -97,  -96,  -38,
         -5,  -29,  -17,  -34,  -99,   -9,  -12,  -90,  -17,  -82,   -9,
         -9,  -33,  -67,  -67,  -83,   -8,  -14,  -45,   -8,  -39,  -55,
        -89,  -95,   -5,  -18,  -88,  -56,  -33,   -9,  -13,  -11,  -95,
        -28,  -86,    0,  -11,   -5,  -71,  -65,  -

In [41]:
np.max(arrays)

101.0