In [2]:
import numpy as np

In [19]:
array=np.array([ 
[186, 749, 793, 970, 835, 253, 380, 780, 478, 253, 644, 970, 655,
 926, 298, 351, 167, 422, 409, 891, 369, 113, 617, 253, 251, 495,
 144, 429, 593, 714, 773, 504, 739, 666, 909, 336, 201, 342, 779,
 131, 394, 654, 671, 442, 423, 161, 683, 562, 323, 545, 478, 592,
 918, 363, 838, 491, 669, 928, 940, 932, 504, 889, 957, 642, 570, 
 947, 194, 217, 493, 771, 452, 146, 228, 759, 821, 387, 129, 319, 
 771, 795, 826, 493, 894, 546, 641, 287, 632, 962, 678, 223, 707, 
 593, 508, 117, 867, 210, 916, 873, 171, 406]])

In [24]:
print(np.max(array))
print(np.min(array))

970
113


In [25]:
np.absolute(array)

array([[186, 749, 793, 970, 835, 253, 380, 780, 478, 253, 644, 970, 655,
        926, 298, 351, 167, 422, 409, 891, 369, 113, 617, 253, 251, 495,
        144, 429, 593, 714, 773, 504, 739, 666, 909, 336, 201, 342, 779,
        131, 394, 654, 671, 442, 423, 161, 683, 562, 323, 545, 478, 592,
        918, 363, 838, 491, 669, 928, 940, 932, 504, 889, 957, 642, 570,
        947, 194, 217, 493, 771, 452, 146, 228, 759, 821, 387, 129, 319,
        771, 795, 826, 493, 894, 546, 641, 287, 632, 962, 678, 223, 707,
        593, 508, 117, 867, 210, 916, 873, 171, 406]])

In [26]:
np.exp(array)

/tmp/ipykernel_14392/3993411681.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(array)


array([[6.00860471e+080,             inf,             inf,
                    inf,             inf, 7.52495525e+109,
        1.07622512e+165,             inf, 3.91527571e+207,
        7.52495525e+109, 4.84893481e+279,             inf,
        2.90325810e+284,             inf, 2.62878826e+129,
        2.73755686e+152, 3.36649891e+072, 1.87185138e+183,
        4.23100071e+177,             inf, 1.79747899e+160,
        1.18925902e+049, 9.11371271e+267, 7.52495525e+109,
        1.01839195e+109, 9.45732997e+214, 3.45466066e+062,
        2.05273429e+186, 3.44054917e+257,             inf,
                    inf, 7.66335385e+218,             inf,
        1.73830087e+289,             inf, 8.37424995e+145,
        1.96422332e+087, 3.37841355e+148,             inf,
        7.80867107e+056, 1.29427294e+171, 1.06804897e+284,
        2.57986724e+291, 9.08157139e+191, 5.08821958e+183,
        8.34471649e+069, 4.19885754e+296, 1.18440118e+244,
        1.89285634e+140, 4.90334710e+236, 3.91527571e+20

In [27]:
np.sqrt(array)

array([[13.6381817 , 27.36786437, 28.16025568, 31.144823  , 28.89636655,
        15.90597372, 19.49358869, 27.92848009, 21.86321111, 15.90597372,
        25.37715508, 31.144823  , 25.59296778, 30.43024811, 17.2626765 ,
        18.734994  , 12.92284798, 20.54263858, 20.22374842, 29.84962311,
        19.20937271, 10.63014581, 24.8394847 , 15.90597372, 15.84297952,
        22.24859546, 12.        , 20.71231518, 24.35159132, 26.72077843,
        27.80287755, 22.44994432, 27.18455444, 25.8069758 , 30.14962686,
        18.33030278, 14.17744688, 18.49324201, 27.91057147, 11.44552314,
        19.84943324, 25.57342371, 25.90366769, 21.02379604, 20.5669638 ,
        12.68857754, 26.13426869, 23.70653918, 17.97220076, 23.34523506,
        21.86321111, 24.33105012, 30.29851482, 19.05255888, 28.94822965,
        22.15851981, 25.86503431, 30.46309242, 30.65941943, 30.52867504,
        22.44994432, 29.81610303, 30.9354166 , 25.33771892, 23.87467277,
        30.77336511, 13.92838828, 14.73091986, 22.2

In [29]:
np.sign(array)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.sin(array)

array([[-0.60202394,  0.96381146,  0.9683795 ,  0.68319568, -0.61599297,
         0.99482373,  0.13232187,  0.77392886,  0.45993026,  0.99482373,
         0.02649089,  0.68319568,  0.99975651,  0.6960152 ,  0.43613763,
        -0.75678279, -0.47555019,  0.85553559,  0.55881405, -0.93643025,
        -0.99061148, -0.09718191,  0.94830128,  0.99482373, -0.32159386,
        -0.9802337 , -0.49102159,  0.98514108,  0.68965428, -0.7568419 ,
         0.16741514,  0.97465539, -0.66367898, -0.01764165, -0.88182727,
         0.14984741, -0.06189025,  0.42013968, -0.11472492, -0.81160339,
        -0.96380342,  0.52160244, -0.96377931,  0.82180066,  0.89791441,
        -0.70240779, -0.95639354,  0.33827666,  0.55140153, -0.99780128,
         0.45993026,  0.98196357,  0.60911575, -0.98935386,  0.72099594,
         0.79045167,  0.15856314, -0.94254467, -0.61611169,  0.868921  ,
         0.97465539,  0.07066203,  0.92678454,  0.89795421, -0.98025158,
        -0.98196927, -0.70238633, -0.22808161,  0.2

In [31]:
np.cos(array)

array([[-0.79847804,  0.26658483,  0.24948174, -0.73023535,  0.78775165,
        -0.10161569, -0.9912068 ,  0.63327255,  0.88795504, -0.10161569,
        -0.99964905, -0.73023535,  0.02206648, -0.71802705, -0.89987997,
         0.65366643, -0.87968859,  0.51774401,  0.82929299,  0.3508538 ,
        -0.13670736,  0.99526664,  0.31737153, -0.10161569,  0.94687771,
         0.19784312,  0.8711474 , -0.17174704, -0.72413878, -0.65359799,
         0.98588649,  0.22371157, -0.74801752,  0.99984437, -0.47157255,
        -0.98870914,  0.99808296, -0.90745945,  0.9933973 ,  0.58420882,
        -0.26661388,  0.85318866,  0.26670104, -0.56977511, -0.44017009,
        -0.71177476, -0.29208115, -0.94104671, -0.83423998, -0.06627678,
         0.88795504,  0.18907022,  0.79308134,  0.14552986, -0.69293929,
         0.61252441, -0.98734884, -0.33408015, -0.7876588 , -0.4949508 ,
         0.22371157, -0.99750031, -0.37559341,  0.44008889, -0.19775448,
        -0.18904062,  0.71179593, -0.97364202, -0.9

In [32]:
np.tan(array)

array([[ 7.53964302e-01,  3.61540255e+00,  3.88156471e+00,
        -9.35582867e-01, -7.81963411e-01, -9.79006006e+00,
        -1.33495725e-01,  1.22211024e+00,  5.17965703e-01,
        -9.79006006e+00, -2.65001866e-02, -9.35582867e-01,
         4.53065646e+01, -9.69343987e-01, -4.84662001e-01,
        -1.15775073e+00,  5.40589239e-01,  1.65242971e+00,
         6.73843932e-01, -2.66900416e+00,  7.24621922e+00,
        -9.76440909e-02,  2.98798470e+00, -9.79006006e+00,
        -3.39636110e-01, -4.95460081e+00, -5.63649267e-01,
        -5.73600042e+00, -9.52378615e-01,  1.15796240e+00,
         1.69811779e-01,  4.35675005e+00,  8.87250587e-01,
        -1.76443917e-02,  1.86997159e+00, -1.51558634e-01,
        -6.20091246e-02, -4.62984526e-01, -1.15487453e-01,
        -1.38923509e+00,  3.61497843e+00,  6.11356507e-01,
        -3.61370663e+00, -1.44232461e+00, -2.03992600e+00,
         9.86839980e-01,  3.27441035e+00, -3.59468514e-01,
        -6.60962727e-01,  1.50550656e+01,  5.17965703e-0

In [43]:
np.zeros((10,100))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.